context:
  version: 0.1.0

package:
  name: python-toon
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-toon/python_toon-${{ version }}.tar.gz
    sha256: 6433d00fecd5e1b3a9654c0c5230278943fc9d93df1572dd0283f85bbd2a7d6a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - toon
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/xaviviro/python-toon
  summary: Token-Oriented Object Notation (TOON) encoder for Python - Optimized data format for LLMs

extra:
  recipe-maintainers:
    - moritzwilksch
