context:
  version: "0.1.1"

package:
  name: python-toon
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-toon/python_toon-${{ version }}.tar.gz
    sha256: 3974182d021b0ef4f24112bee7c2ca42686bab790524cc89c2cddbfff7145a02

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - toon
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/xaviviro/python-toon
  summary: Token-Oriented Object Notation (TOON) encoder for Python - Optimized data format for LLMs

extra:
  recipe-maintainers:
    - moritzwilksch
