context:
  version: "0.2.0"

package:
  name: python-toon
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-toon/python_toon-${{ version }}.tar.gz
    sha256: 1b9fcb3fa225cb7973a2637834de08a26236013ab04da0cf80c4af73e141ccf2

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - toon
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/xaviviro/python-toon
  summary: Token-Oriented Object Notation (TOON) encoder for Python - Optimized data format for LLMs

extra:
  recipe-maintainers:
    - moritzwilksch
